In [6]:
import numpy as numpy

In [9]:
arr = numpy.array([1,2,34,5,6])
print(arr)
arr2 = numpy.array([[1,4,5,6],[3,45,66,6]])
print(arr2)

[ 1  2 34  5  6]
[[ 1  4  5  6]
 [ 3 45 66  6]]


## list

In [10]:
list  = [2,3,45]
print(list*2)
list_arr = numpy.array([2,34,4,55,5])
print(list_arr * 2)

[2, 3, 45, 2, 3, 45]
[  4  68   8 110  10]


In [2]:
import numpy as np


# Generate random marks for 50 students in 3 subjects
np.random.seed(42)  # For reproducibility
maths_marks = np.random.randint(40, 100, 50)
science_marks = np.random.randint(35, 100, 50)
english_marks = np.random.randint(30, 100, 50)

# Create a NumPy array
marks = np.array([maths_marks, science_marks, english_marks])

# Compute statistics
mean_marks = np.mean(marks, axis=1)
median_marks = np.median(marks, axis=1)
std_dev = np.std(marks, axis=1)
highest_marks = np.max(marks, axis=1)
lowest_marks = np.min(marks, axis=1)

# Print Results
subjects = ["Maths", "Science", "English"]
for i, subject in enumerate(subjects):
    print(f"{subject}: Mean = {mean_marks[i]}, Median = {median_marks[i]}, Std Dev = {std_dev[i]}")
    print(f"Highest = {highest_marks[i]}, Lowest = {lowest_marks[i]}\n")



Maths: Mean = 71.86, Median = 70.5, Std Dev = 17.522568304903253
Highest = 99, Lowest = 41

Science: Mean = 65.5, Median = 68.5, Std Dev = 21.13977294107011
Highest = 99, Lowest = 35

English: Mean = 62.7, Median = 62.5, Std Dev = 18.964440408301005
Highest = 95, Lowest = 30



In [20]:
import numpy as numpy

Random = numpy.random.randint(10,50,100)
numbers = np.where(Random  > 20)
summ = np.sum(numbers)
print(summ)

3199
